mju-likelion/12th-hackathon-team1-server

build.gradle, src/main/java/com/hackathonteam1/refreshrator/dto/ErrorResponseDto.java, src/main/java/com/hackathonteam1/refreshrator/dto/ResponseDto.java, src/main/java/com/hackathonteam1/refreshrator/exception/ConflictException.java, src/main/java/com/hackathonteam1/refreshrator/exception/CustomException.java, src/main/java/com/hackathonteam1/refreshrator/exception/DtoValidationException.java, src/main/java/com/hackathonteam1/refreshrator/exception/ForbiddenException.java, src/main/java/com/hackathonteam1/refreshrator/exception/NotFoundException.java, src/main/java/com/hackathonteam1/refreshrator/exception/UnauthorizedException.java, src/main/java/com/hackathonteam1/refreshrator/exception/advice/ExceptionController.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
예외 처리를 위한 Exception 및 ResponseDTO 작성
Closes #7
=> Feature/#7 예외 처리를 위한 Exception 및 ResponseDTO 작성

build.gradle, src/main/java/com/hackathonteam1/refreshrator/RefreshratorApplication.java, src/main/java/com/hackathonteam1/refreshrator/entity/BaseEntity.java, src/main/java/com/hackathonteam1/refreshrator/entity/Fridge.java, src/main/java/com/hackathonteam1/refreshrator/entity/FridgeItem.java, src/main/java/com/hackathonteam1/refreshrator/entity/Image.java, src/main/java/com/hackathonteam1/refreshrator/entity/Ingredient.java, src/main/java/com/hackathonteam1/refreshrator/entity/IngredientRecipe.java, src/main/java/com/hackathonteam1/refreshrator/entity/Recipe.java, src/main/java/com/hackathonteam1/refreshrator/entity/RecipeLike.java, src/main/java/com/hackathonteam1/refreshrator/entity/User.java
=> Feature/#3 모델 Entity 생성

src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java, src/main/java/com/hackathonteam1/refreshrator/dto/request/SigninDto.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/repository/UserRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
=> Feature/#10 회원가입 기능

src/main/java/com/hackathonteam1/refreshrator/repository/FridgeRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
회원가입시 냉장고 생성 기능 추가 
closes #16
=> Feature/#16 회원가입시 냉장고 생성 기능 추가

src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/RegisterRecipeDto.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/ingredient/IngredientDto.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/DetailRecipeDto.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/repository/IngredientRecipeRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
레시피 상세 조회 API 구현
레시피 조회 시에 나올 이미지는 추후 추가할 예정
Closes #20
=> Feature/#20 레시피 상세 조회 API

src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/request/fridge/AddFridgeDto.java, src/main/java/com/hackathonteam1/refreshrator/entity/FridgeItem.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/repository/FridgeItemRepository.java, src/main/java/com/hackathonteam1/refreshrator/repository/FridgeRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
=> Feature/#18 냉장고에 재료추가 API

src/main/java/com/hackathonteam1/refreshrator/exception/advice/ExceptionController.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java
예외처리 누락 부분 추가 및 수정
예상 불가한 500번대 예외 처리 추가, Pattern의 예외처리 MetaDataAccessException -> MethodArgumentNotValidException으로 수정
Closes #24
=> Feature/24 예외처리 누락 부분 추가 및 수정

src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/request/recipe/ModifyRecipeDto.java, src/main/java/com/hackathonteam1/refreshrator/entity/Recipe.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
레시피명 및 조리법 수정 API 구현
레시피명 및 레시피 내용 수정
레시피 재료 수정은 따로 API를 구현할 예정
Closes #22
=> Feature/#22 레시피명 및 조리법 수정 API

src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/request/fridge/AddFridgeDto.java, src/main/java/com/hackathonteam1/refreshrator/entity/FridgeItem.java, src/main/java/com/hackathonteam1/refreshrator/entity/User.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
냉장고에 있는 재료 수정 API
URI:  /fridge/ingredients/{ingredient_id} 
closes #29
=> Feature/#29 냉장고에 있는 재료 수정 API

src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java, src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
냉장고에서 재료삭제 API
경로: /fridge/ingredients/{ingredient_id}
closes #32
=> Feature/#32 냉장고에서 재료삭제 API 

src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java
로그아웃 API
경로:  /auth/logout
closes #34
=> Feature/#34 로그아웃 API

src/main/java/com/hackathonteam1/refreshrator/controller/IngredientController.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/ingredient/IngredientListDto.java, src/main/java/com/hackathonteam1/refreshrator/service/IngredientService.java
=> Feature/#39 DB에 있는 재료 조회 API

src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java, src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
=> Feature/#13 레시피 삭제 API 

src/main/java/com/hackathonteam1/refreshrator/controller/IngredientController.java, src/main/java/com/hackathonteam1/refreshrator/service/IngredientService.java
=> Feature/#45 DB에 있는 재료 검색 API

src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java, src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java, src/main/java/com/hackathonteam1/refreshrator/entity/Fridge.java, src/main/java/com/hackathonteam1/refreshrator/entity/User.java, src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java
회원탈퇴 API
경로는 auth/leave 
closes #51
=> Feature/#51 회원탈퇴 API

src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/fridgeItem/FridgeItemResponseData.java, src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
냉장고에 있는 재료 단건조회 API
closes #49
=> Feature/#49 냉장고에 있는 재료 단건조회 API

src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/fridge/FridgeItemDto.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/fridge/FridgeItemListDto.java, src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
냉장고에 있는 재료 전체 조회 API
Closed #52
=> Feature/#52 냉장고에 있는 재료 전체 조회 API

build.gradle, src/main/java/com/hackathonteam1/refreshrator/config/S3Config.java, src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/file/ImageDto.java, src/main/java/com/hackathonteam1/refreshrator/exception/FileStorageException.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/repository/ImageRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java, src/main/java/com/hackathonteam1/refreshrator/util/S3Uploader.java
=> Feature/ #61 이미지 생성 API

src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java, src/main/java/com/hackathonteam1/refreshrator/entity/User.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/repository/RecipeLikeRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
레시피 좋아요 추가 API
User RecipeLike의 FetchType을 Eager에서 Lazy로 가능하도록 수정
Closed #62
=> Feature/#62 레시피에 좋아요 추가 API

src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java, src/main/java/com/hackathonteam1/refreshrator/controller/AuthController.java, src/main/java/com/hackathonteam1/refreshrator/controller/FridgeController.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeListReponseDto.java, src/main/java/com/hackathonteam1/refreshrator/dto/response/recipe/RecipeResponseDto.java, src/main/java/com/hackathonteam1/refreshrator/repository/RecipeLikeRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java, src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java
자신이 좋아요 누른 레시피 목록 조회 API
Closed #69
=> Feature/#69 자신이 좋아요 누른 레시피 목록 조회 API

src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
merge 과정에서 conflict 수작업으로 수정하면서 생긴 import 누락 추가
Closed #72
=> Fix/#72 누락된 import 추가

src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java, src/main/java/com/hackathonteam1/refreshrator/entity/FridgeItem.java, src/main/java/com/hackathonteam1/refreshrator/repository/RecipeRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
레시피 추천 API
/recipes/recommendations?page=0&size=10&match=2147483647&type=newest
page: 요청하는 페이지
size: 포함되는 객체 수
match: 냉장고 속 재료가 레시피 재료 중 최소 몇 개가 일치하는지, 혹은 재료가 전부 포함되는 경우. default는 Integer.Max_Value로 값을 주지 않을 경우 기본으로 재료가 전부 포함되는 레시피만 보여줌
type: 정렬 방식. newest || popularity
Closes #59
=> Feature/#59 레시피 추천 API

src/main/java/com/hackathonteam1/refreshrator/controller/RecipeController.java, src/main/java/com/hackathonteam1/refreshrator/exception/errorcode/ErrorCode.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
=> Feature/#64 레시피 좋아요 삭제 API

src/main/java/com/hackathonteam1/refreshrator/authentication/AuthenticationInterceptor.java, src/main/java/com/hackathonteam1/refreshrator/config/CorsConfig.java
Cors 설정
OPTIONS에는 인증을 true로 설정
=> Feature/ cors 설정 추가 

Dockerfile, src/test/java/com/hackathonteam1/refreshrator/RefreshratorApplicationTests.java
배포
테스트 파일 때문에 Build가 되지 않아 test파일을 주석 처리함.
Closes #48
=> Feature/#48 배포 작업

src/main/java/com/hackathonteam1/refreshrator/controller/HealthController.java
Health 컨트롤러 작성
aws 대상 그룹에서 EC2들의 상태를 확인하기 위해 사용하는 /health uri에 응답을 제공하도록 컨트롤러 작성.
Closes #82
=> Feature/#82  HealthController 작성 

src/main/java/com/hackathonteam1/refreshrator/service/AuthService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
페이지네이션 예외 처리 추가
누락된 몇몇 존재하지 않는 페이지 요청 시 예외 작성. -> 기존에 존재하던 checkValidPage 메서드를 사용하여 처리함.
Closes #84
=> Feature/#84 페이지네이션 사용 시 누락된 예외처리 작성 

.github/workflows/gradle.yml
CI/CD 적용 
CI/CD 적용을 위한 gradle.yml 작성
main브랜치에 merge 시 자동으로 재배포되도록 설정.
=> Feature/#86 CI/CD 적용  

src/main/java/com/hackathonteam1/refreshrator/config/AuthenticationConfig.java, src/main/java/com/hackathonteam1/refreshrator/controller/UserController.java, src/main/java/com/hackathonteam1/refreshrator/repository/RecipeRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeService.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
=> Feature/#88 자신이 작성한 레시피 조회 API

src/main/java/com/hackathonteam1/refreshrator/dto/response/fridge/FridgeItemDto.java, src/main/java/com/hackathonteam1/refreshrator/service/FridgeService.java
냉장고에 있는 재료 조회 DTO 수정
유통 기한 추가
Closes #93
=> Refactor/#93 냉장고에 있는 재료 조회 DTO 수정

.github/workflows/gradle.yml
CI/CD workflow에 도커 네트워크 연결 추가
기존에 수동으로 docker network 연결을 해주던 부분을 workflow에 추가함. 
사용자 정의 네트워크 my-network는 이미 생성되어 있기 때문에 컨테이너 run 시 자동으로 연결되도록 설정함.
Closes #100
=> Feature/#100 workflow에 도커 네트워크 연결 추가 

src/main/java/com/hackathonteam1/refreshrator/repository/ImageRepository.java, src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
레시피 삭제 시 자동으로 S3에서 이미지 삭제되도록 수정
Closes #102
=> Feature/#102 레시피 삭제 시 자동으로 S3에서 이미지 삭제되도록 수정

src/main/java/com/hackathonteam1/refreshrator/service/RecipeServiceImpl.java
레시피 좋아요 삭제 관련 오류 수정
Closes #109
=> Feature/#109 레시피 좋아요 삭제 오류 수정

.github/workflows/gradle.yml
EC2를 추가하며 git workflow수정
애플리케이션 EC2를 하나 추가하며 workflow 수정 
redis도 별도의 EC2로 분리함.
=> Feature/#111 EC2를 추가하며 git workflow수정
